version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:2.3.2
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=1
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/var/lib/localstack/data
    volumes:
      - "./init.sh:/etc/localstack/init/ready.d/init.sh"
      - "/c/tmp/localstack-data:/var/lib/localstack/data"
      - "//./pipe/docker_engine://./pipe/docker_engine"
